trigger: none

pool:
  name: selfhosted-pool

steps:
  - task: PowerShell@2
    inputs:
      targetType: "inline"
      script: |
        $githubToken = "${{ parameters.GitHubConnection.token }}"      
        $workflowType = "azure-devops-trigger"
        $apiUrl = "https://api.github.com/repos/whatdoIputhere/ado-ghactions/dispatches"

        $inputs = @{
          appname = "${env:APPNAME}"
          env = "${env:ENV}"
        }

        $body = @{
          event_type = $workflowType
          client_payload = $inputs
        } | ConvertTo-Json

        Invoke-RestMethod -Method Post -Uri $apiUrl -Headers @{
          Authorization = "token $githubToken"
          Accept = "application/vnd.github.v3+json"
        } -Body $body
    env:
      githubToken: ${{ parameters.GitHubConnection.token }}