name: Action triggered by Azure DevOps

on:
  repository_dispatch:
    types: [azure-devops-trigger]

jobs:
  Ado-Triggered-Job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo inputs
        run: |
          echo "App name: ${{ github.event.inputs.appname }}"
          echo "Env: ${{ github.event.inputs.env }}"